	insert into bancos(numerobanco,nomebanco,datainclusao) values ('332','Acesso Soluções de Pagamento S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('117','ADVANCED CORRETORA DE CÂMBIO LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('272','AGK CORRETORA DE CAMBIO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('349','AMAGGI S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('188','ATIVA INVESTIMENTOS S.A. CORRETORA DE TÍTULOS, CÂMBIO E VALORES',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('280','Avista S.A. Crédito, Financiamento e Investimento',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('80','B&T CORRETORA DE CAMBIO LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('654','Banco A.J.Renner S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('246','Banco ABC Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('75','Banco ABN AMRO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('121','Banco Agibank S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('25','Banco Alfa S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('65','Banco Andbank (Brasil) S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('213','Banco Arbi S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('96','Banco B3 S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('24','Banco BANDEPE S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('330','Banco Bari de Investimentos e Financiamentos S/A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('318','Banco BMG S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('752','Banco BNP Paribas Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('107','Banco BOCOM BBM S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('63','Banco Bradescard S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('36','Banco Bradesco BBI S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('122','Banco Bradesco BERJ S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('394','Banco Bradesco Financiamentos S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('237','Banco Bradesco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('218','Banco BS2 S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('208','Banco BTG Pactual S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('336','Banco C6 S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('473','Banco Caixa Geral - Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('412','Banco Capital S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('40','Banco Cargill S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('739','Banco Cetelem S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('233','Banco Cifra S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('745','Banco Citibank S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('241','Banco Clássico S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('756','Banco Cooperativo do Brasil S.A. - BANCOOB',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('748','Banco Cooperativo Sicredi S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('222','Banco Credit Agricole Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('505','Banco Credit Suisse (Brasil) S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('69','Banco Crefisa S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('266','Banco Cédula S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('3','Banco da Amazônia S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('83','Banco da China Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('707','Banco Daycoval S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('300','Banco de La Nacion Argentina',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('495','Banco de La Provincia de Buenos Aires',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('335','Banco Digio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('1','Banco do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('47','Banco do Estado de Sergipe S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('37','Banco do Estado do Pará S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('41','Banco do Estado do Rio Grande do Sul S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('4','Banco do Nordeste do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('265','Banco Fator S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('224','Banco Fibra S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('626','Banco Ficsa S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('94','Banco Finaxis S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('612','Banco Guanabara S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('12','Banco Inbursa S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('604','Banco Industrial do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('653','Banco Indusval S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('77','Banco Inter S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('249','Banco Investcred Unibanco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('479','Banco ItauBank S.A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('184','Banco Itaú BBA S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('29','Banco Itaú Consignado S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('376','Banco J. P. Morgan S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('74','Banco J. Safra S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('217','Banco John Deere S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('76','Banco KDB S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('757','Banco KEB HANA do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('600','Banco Luso Brasileiro S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('389','Banco Mercantil do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('370','Banco Mizuho do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('746','Banco Modal S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('66','Banco Morgan Stanley S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('456','Banco MUFG Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('243','Banco Máxima S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('7','Banco Nacional de Desenvolvimento Econômico e Social - BNDES',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('169','Banco Olé Bonsucesso Consignado S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('79','Banco Original do Agronegócio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('212','Banco Original S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('712','Banco Ourinvest S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('623','Banco PAN S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('611','Banco Paulista S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('643','Banco Pine S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('747','Banco Rabobank International Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('633','Banco Rendimento S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('741','Banco Ribeirão Preto S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('120','Banco Rodobens S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('422','Banco Safra S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('33','Banco Santander (Brasil) S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('743','Banco Semear S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('754','Banco Sistema S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('630','Banco Smartbank S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('366','Banco Société Générale Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('637','Banco Sofisa S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('464','Banco Sumitomo Mitsui Brasileiro S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('82','Banco Topázio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('18','Banco Tricury S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('634','Banco Triângulo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('655','Banco Votorantim S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('610','Banco VR S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('119','Banco Western Union do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('124','Banco Woori Bank do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('348','Banco XP S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('81','BancoSeguro S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('21','BANESTES S.A. Banco do Estado do Espírito Santo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('755','Bank of America Merrill Lynch Banco Múltiplo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('268','BARI COMPANHIA HIPOTECÁRIA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('250','BCV - Banco de Crédito e Varejo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('144','BEXS Banco de Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('253','Bexs Corretora de Câmbio S/A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('134','BGC LIQUIDEZ DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('17','BNY Mellon Banco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('301','BPP Instituição de Pagamento S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('126','BR Partners Banco de Investimento S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('70','BRB - Banco de Brasília S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('92','Brickell S.A. Crédito',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('173','BRL Trust Distribuidora de Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('142','Broker Brasil Corretora de Câmbio Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('292','BS2 Distribuidora de Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('104','Caixa Econômica Federal',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('309','CAMBIONET CORRETORA DE CÂMBIO LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('288','CAROL DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('130','CARUANA S.A. - SOCIEDADE DE CRÉDITO, FINANCIAMENTO E INVESTIMENTO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('159','Casa do Crédito S.A. Sociedade de Crédito ao Microempreendedor',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('114','Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('91','CENTRAL DE COOPERATIVAS DE ECONOMIA E CRÉDITO MÚTUO DO ESTADO DO RIO GRANDE DO S',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('320','China Construction Bank (Brasil) Banco Múltiplo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('477','Citibank N.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('180','CM CAPITAL MARKETS CORRETORA DE CÂMBIO, TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('127','Codepe Corretora de Valores e Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('163','Commerzbank Brasil S.A. - Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('133','CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS DE CRÉDITO E ECONOMIA FAMILIAR E',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('136','CONFEDERAÇÃO NACIONAL DAS COOPERATIVAS CENTRAIS UNICRED LTDA. - UNICRED DO BRASI',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('60','Confidence Corretora de Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('85','Cooperativa Central de Crédito - AILOS',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('97','Cooperativa Central de Crédito Noroeste Brasileiro Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('279','COOPERATIVA DE CREDITO RURAL DE PRIMAVERA DO LESTE',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('16','COOPERATIVA DE CRÉDITO MÚTUO DOS DESPACHANTES DE TRÂNSITO DE SANTA CATARINA E RI',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('281','Cooperativa de Crédito Rural Coopavel',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('322','Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('286','COOPERATIVA DE CRÉDITO RURAL DE OURO SULCREDI/OURO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('273','Cooperativa de Crédito Rural de São Miguel do Oeste - Sulcredi/São Miguel',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('98','Credialiança Cooperativa de Crédito Rural',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('10','CREDICOAMO CREDITO RURAL COOPERATIVA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('89','CREDISAN COOPERATIVA DE CRÉDITO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('11','CREDIT SUISSE HEDGING-GRIFFO CORRETORA DE VALORES S.A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('342','Creditas Sociedade de Crédito Direto S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('321','CREFAZ SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORTE LT',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('289','DECYSEO CORRETORA DE CAMBIO LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('487','Deutsche Bank S.A. - Banco Alemão',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('140','Easynvest - Título Corretora de Valores SA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('149','Facta Financeira S.A. - Crédito Financiamento e Investimento',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('196','FAIR CORRETORA DE CAMBIO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('343','FFA SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('331','Fram Capital Distribuidora de Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('285','Frente Corretora de Câmbio Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('278','Genial Investimentos Corretora de Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('364','GERENCIANET PAGAMENTOS DO BRASIL LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('138','Get Money Corretora de Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('64','Goldman Sachs do Brasil Banco Múltiplo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('177','Guide Investimentos S.A. Corretora de Valores',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('146','GUITTA CORRETORA DE CAMBIO LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('78','Haitong Banco de Investimento do Brasil S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('62','Hipercard Banco Múltiplo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('189','HS FINANCEIRA S/A CREDITO, FINANCIAMENTO E INVESTIMENTOS',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('269','HSBC Brasil S.A. - Banco de Investimento',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('271','IB Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('157','ICAP do Brasil Corretora de Títulos e Valores Mobiliários Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('132','ICBC do Brasil Banco Múltiplo S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('492','ING Bank N.V.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('139','Intesa Sanpaolo Brasil S.A. - Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('652','Itaú Unibanco Holding S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('341','Itaú Unibanco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('488','JPMorgan Chase Bank',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('399','Kirton Bank S.A. - Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('293','Lastro RDV Distribuidora de Títulos e Valores Mobiliários Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('105','Lecca Crédito, Financiamento e Investimento S/A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('145','LEVYCAM - CORRETORA DE CAMBIO E VALORES LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('113','Magliano S.A. Corretora de Cambio e Valores Mobiliarios',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('323','MERCADOPAGO.COM REPRESENTACOES LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('274','MONEY PLUS SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E A EMPRESA DE PEQUENO PORT',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('259','MONEYCORP BANCO DE CÂMBIO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('128','MS Bank S.A. Banco de Câmbio',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('354','NECTON INVESTIMENTOS S.A. CORRETORA DE VALORES MOBILIÁRIOS E COMMODITIES',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('191','Nova Futura Corretora de Títulos e Valores Mobiliários Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('753','Novo Banco Continental S.A. - Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('260','Nu Pagamentos S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('111','OLIVEIRA TRUST DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIARIOS S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('319','OM DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('613','Omni Banco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('290','Pagseguro Internet S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('254','Paraná Banco S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('326','PARATI - CREDITO, FINANCIAMENTO E INVESTIMENTO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('194','PARMETAL DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('174','PERNAMBUCANAS FINANCIADORA S.A. - CRÉDITO, FINANCIAMENTO E INVESTIMENTO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('315','PI Distribuidora de Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('100','Planner Corretora de Valores S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('125','Plural S.A. - Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('108','PORTOCRED S.A. - CREDITO, FINANCIAMENTO E INVESTIMENTO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('306','PORTOPAR DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('93','PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORT',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('329','QI Sociedade de Crédito Direto S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('283','RB CAPITAL INVESTIMENTOS DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LIMITADA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('101','RENASCENCA DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('270','Sagitur Corretora de Câmbio Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('751','Scotiabank Brasil S.A. Banco Múltiplo',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('276','Senff S.A. - Crédito, Financiamento e Investimento',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('545','SENSO CORRETORA DE CAMBIO E VALORES MOBILIARIOS S.A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('190','SERVICOOP - COOPERATIVA DE CRÉDITO DOS SERVIDORES PÚBLICOS ESTADUAIS DO RIO GRAN',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('183','SOCRED S.A. - SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO P',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('365','SOLIDUS S.A. CORRETORA DE CAMBIO E VALORES MOBILIARIOS',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('299','SOROCRED CRÉDITO, FINANCIAMENTO E INVESTIMENTO S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('14','State Street Brasil S.A. - Banco Comercial',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('197','Stone Pagamentos S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('340','Super Pagamentos e Administração de Meios Eletrônicos S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('307','Terra Investimentos Distribuidora de Títulos e Valores Mobiliários Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('352','TORO CORRETORA DE TÍTULOS E VALORES MOBILIÁRIOS LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('95','Travelex Banco de Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('143','Treviso Corretora de Câmbio S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('131','TULLETT PREBON BRASIL CORRETORA DE VALORES E CÂMBIO LTDA',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('129','UBS Brasil Banco de Investimento S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('15','UBS Brasil Corretora de Câmbio, Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('99','UNIPRIME CENTRAL - CENTRAL INTERESTADUAL DE COOPERATIVAS DE CREDITO LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('84','Uniprime Norte do Paraná - Coop de Economia e Crédito Mútuo dos Médicos',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('373','UP.P SOCIEDADE DE EMPRÉSTIMO ENTRE PESSOAS S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('298','Vips Corretora de Câmbio Ltda.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('296','VISION S.A. CORRETORA DE CAMBIO',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('367','VITREO DISTRIBUIDORA DE TÍTULOS E VALORES MOBILIÁRIOS S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('310','VORTX DISTRIBUIDORA DE TITULOS E VALORES MOBILIARIOS LTDA.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('102','XP INVESTIMENTOS CORRETORA DE CÂMBIO,TÍTULOS E VALORES MOBILIÁRIOS S/A',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('325','Órama Distribuidora de Títulos e Valores Mobiliários S.A.',getdate())
	insert into bancos(numerobanco,nomebanco,datainclusao) values ('355','ÓTIMO SOCIEDADE DE CRÉDITO DIRETO S.A.',getdate())