USE [master]
GO

/****** Object:  Database [Banco]    Script Date: 03/05/2021 16:54:04 ******/
CREATE DATABASE [Banco]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Banco', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Banco.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Banco_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Banco_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Banco].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Banco] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Banco] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Banco] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Banco] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Banco] SET ARITHABORT OFF 
GO

ALTER DATABASE [Banco] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Banco] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Banco] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Banco] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Banco] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Banco] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Banco] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Banco] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Banco] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Banco] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Banco] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Banco] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Banco] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Banco] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Banco] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Banco] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Banco] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Banco] SET RECOVERY FULL 
GO

ALTER DATABASE [Banco] SET  MULTI_USER 
GO

ALTER DATABASE [Banco] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Banco] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Banco] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Banco] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Banco] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Banco] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Banco] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Banco] SET  READ_WRITE 
GO

